apiVersion: promptkit.altairalabs.ai/v1alpha1
kind: Scenario
metadata:
  name: api-documentation-scenarios
spec:
  task_type: code-analysis
  description: "Test scenarios for API documentation to source code mapping"

  turns:
    - role: user
      content: |
        Analyze this documentation and identify the relevant source files:
        
        Document Path: docs/api/task-manager.md
        Document Title: Task Manager API Reference
        
        # Task Manager API
        
        The Task Manager library provides a simple interface for managing tasks.
        
        ## TaskManager Class
        
        ```typescript
        const manager = new TaskManager();
        manager.createTask({ title: "New task", priority: "high" });
        ```
        
        ### Methods
        - createTask(options: CreateTaskOptions): Task
        - updateTask(id: string, options: UpdateTaskOptions): Task
        - filterTasks(filter: TaskFilter): Task[]
        - getStatistics(): TaskStatistics
        
        ## Types
        - Task, TaskStatus (TODO, IN_PROGRESS, DONE), TaskPriority (LOW, MEDIUM, HIGH)

      assertions:
        - type: is_valid_json
          params:
            allow_wrapped: true
            extract_json: true
          message: "Response should be valid JSON"
        
        - type: json_schema
          params:
            schema:
              type: object
              required: ["files", "folders", "confidence", "reasoning"]
              properties:
                files:
                  type: array
                  items:
                    type: string
                folders:
                  type: array
                  items:
                    type: string
                confidence:
                  type: string
                  enum: ["high", "medium", "low"]
                reasoning:
                  type: array
                  items:
                    type: string
            allow_wrapped: true
            extract_json: true
          message: "Response should match expected schema"
        
        - type: json_path
          params:
            jmespath_expression: "files[?@ == 'src/task-manager.ts']"
            min_results: 1
            allow_wrapped: true
            extract_json: true
          message: "Should identify TaskManager class file"
        
        - type: json_path
          params:
            jmespath_expression: "files[?@ == 'src/types.ts']"
            min_results: 1
            allow_wrapped: true
            extract_json: true
          message: "Should identify types definition file"
        
        - type: json_path
          params:
            jmespath_expression: "confidence"
            expected: "high"
            allow_wrapped: true
            extract_json: true
          message: "Should have high confidence for API docs"
